#!/bin/bash

source setupfintest

./finlisp.py \
    --no-default-config \
    --output-dir "results" \
    --config $CONFIGDIR/accounts.yaml \
    --config $CONVDIR/conversions.yaml \
    adjust.lisp
