(let* ((period (getenv "PERIOD" "full"))
       (output-dir (format "/tmp/finrun-%s" period))
       (statement-basic (read-canonical
                         (format "~/common/qs/qs-scratch/handelsbanken-%s.csv"
                                 period)))
       (handelsbanken-as-account (account "HB current statement" statement-basic))
       (financisto-basic (read-canonical
                          (format "~/common/qs/qs-scratch/financisto-%s.csv"
                                  period)))
       (financisto-as-account (account "Handelsbanken current account" financisto-basic))
       (financisto-monthly (account-to-sheet (by-month financisto-as-account)))
       (handelsbanken-monthly (account-to-sheet (by-month handelsbanken-as-account)))
       (monthly-difference (subtract-cells handelsbanken-monthly financisto-monthly))
       (non-trivial-monthly-differences (threshold monthly-difference 10))
       (occupied-non-trivial-monthly-differences (occupied-columns non-trivial-monthly-differences))
       (annotated (annotate-matches occupied-non-trivial-monthly-differences statement-basic))
       (update-sheet (make-update-sheet occupied-non-trivial-monthly-differences statement-basic)))
  (make-empty-dir output-dir)
  (write-csv statement-basic "statement-converted.csv")
  (write-csv financisto-basic "financisto-converted.csv")
  (write-csv handelsbanken-monthly "statement-monthly.csv")
  (write-json handelsbanken-monthly "statement-monthly.json")
  (write-csv financisto-monthly "financisto-monthly.csv")
  (write-json financisto-monthly "financisto-monthly.json")
  (write-csv monthly-difference "monthly-difference.csv")
  (write-json monthly-difference "monthly-difference.json")
  (write-csv non-trivial-monthly-differences "non-trivial-monthly-differences.csv")
  (write-json non-trivial-monthly-differences "non-trivial-monthly-differences.json")
  (write-csv occupied-non-trivial-monthly-differences "occupied-non-trivial-monthly-differences.csv")
  (write-json occupied-non-trivial-monthly-differences "occupied-non-trivial-monthly-differences.json")
  (write-csv annotated "annotated.csv")
  (write-json annotated "annotated.json")
  (write-csv update-sheet "update.csv")
  (write-csv (format-sheet update-sheet "financisto") "update-financisto.csv")
  )
