(let* ((period (getenv "PERIOD" "full"))
       (output-dir (format "/tmp/finrun-%s" period))
       (financisto-basic (read-canonical "~/common/finances/finances.csv"))
       (financisto-hb-as-account (account "Handelsbanken current account" financisto-basic))
       (financisto-monthly (by-month financisto-hb-as-account))
       (financisto-hb-monthly (account-to-sheet financisto-monthly))
       (category-tree (categories financisto-basic))
       (category-tree-monthly (by-month category-tree))
       (category-sheet (categorised financisto-basic)))
  (write-csv financisto-hb-as-account "financisto-hb-as-account.csv")
  (write-csv financisto-monthly "financisto-monthly.csv")
  (write-csv financisto-hb-monthly "financisto-hb-monthly.csv")
  (write-csv category-sheet "category-sheet.csv")
  (write-csv category-tree "category-tree.csv")
  (write-csv category-tree-monthly "category-tree-monthly.csv"))
