(let* ((monthly (by-month
                 (fgrep
                  (read-canonical input-file)
                  "GBP" "currency")
                 nil))
       (parentage-table (read-parentage-table "cats.yaml"))
       (classifiers (read-classifier "default-classes.yaml"))
       (by-category (categorised monthly))
       (by-parentage (by-parent monthly parentage-table))
       (by-class (by-classification monthly parentage-table classifiers))
       (by-level-0 (by-hierarchy monthly 0 parentage-table))
       (by-level-1 (by-hierarchy monthly 1 parentage-table))
       (by-level-2 (by-hierarchy monthly 2 parentage-table))
       (by-proportions (proportions by-category)))
  (print "classifiers are:" classifiers)
  (write-csv monthly "/tmp/monthly.csv")
  (write-csv by-category "/tmp/by-category.csv")
  (write-csv by-parentage "/tmp/by-parentage.csv")
  (write-csv by-class "/tmp/by-class.csv")
  (write-csv by-level-0 "/tmp/by-level-0.csv")
  (write-csv by-level-1 "/tmp/by-level-1.csv")
  (write-csv by-level-2 "/tmp/by-level-2.csv")
  (write-csv by-proportions "/tmp/by-proportions.csv"))
