#!/bin/bash

echo Categorising transactions

source setupfintest

echo done setup

./finlisp.py \
    --no-default-config \
    --config $CONFIGDIR/accounts.yaml \
    --config $CONVDIR/conversions.yaml \
    --verbose \
    --output-dir "results" \
    --bind input-file "~/common/finances/finances.csv" \
    chart-categories.lisp
