#!/bin/bash

TRANSACTIONSFILE=${1-$COMMON/finances/finances.csv}
# CLASSIFIERSFILE=default-classes.yaml
CLASSIFIERSFILE=budgetting-classes.yaml
THRESHOLDSFILE=budgetting-thresholds.yaml

echo Categorising transactions

source setupfintest

echo done setup

./finlisp.py \
    --no-default-config \
    --config $CONFIGDIR/accounts.yaml \
    --config $CONVDIR/conversions.yaml \
    --verbose \
    --output-dir "results" \
    --bind input-file $TRANSACTIONSFILE \
    --bind classifiers-file $CLASSIFIERSFILE \
    --bind thresholds-file $THRESHOLDSFILE \
    chart-categories.lisp

echo done classifications

# from https://raymii.org/s/tutorials/GNUplot_tips_for_nice_looking_charts_from_a_CSV_file.html:

# set datafile separator ','

# set xdata time # tells gnuplot the x axis is time data
# set timefmt "%Y-%m-%dT%H:%M:%S" # specify our time string format
# set format x "%H:%M:%S" # otherwise it will show only MM:SS
# set key autotitle columnhead # use the first line as title
# set ylabel "First Y Units" # label for the Y axis
# set xlabel 'Time' # label for the X axis
# set yrange [0:]  
# plot plot.csv using 1:2 with lines, '' using 1:3 with lines

# more examples at https://alvinalexander.com/technology/gnuplot-charts-graphs-examples/
