#!/bin/bash

TRANSACTIONSFILE=${1-$COMMON/finances/finances.csv}

echo Categorising transactions

source setupfintest

echo done setup

./finlisp.py \
    --no-default-config \
    --config $CONFIGDIR/accounts.yaml \
    --config $CONVDIR/conversions.yaml \
    --verbose \
    --output-dir "results" \
    --bind input-file $TRANSACTIONSFILE \
    chart-categories.lisp
