(+ (* 3 4) 5)

(* (+ 3 4) 5)

(let ((a (+ 3 4))
      (b (* 3 4)))
  (/ b a))

(builtins)

(let ((financisto (read-canonical "~/common/qs/qs-scratch/financisto-full.csv"))
      (handelsbanken (read-canonical "~/common/qs/qs-scratch/handelsbanken-full.csv")))
  (print financisto)
  (write-csv financisto "/tmp/financisto-as-csv.csv")
  (print handelsbanken)
  (write-csv handelsbanken "/tmp/handelsbanken-as-csv.csv")
  (let ((app-as-account (account "financisto-from-app" financisto))
        (statement-as-account (account "handelsbanken-from-statement" handelsbanken)))
    (print app-as-account)
    (write-csv app-as-account "/tmp/financisto-as-account.csv")
    (print statement-as-account)
    (write-csv statement-as-account "/tmp/handelsbanken-as-account.csv")
    (let ((app-monthly (by-month app-as-account)))
      (print app-monthly))
    (let ((added (add-sheet app-as-account handelsbanken)))
      (print added))))
