(+ (* 3 4) 5)

(* (+ 3 4) 5)

(let ((a (+ 3 4))
      (b (* 3 4)))
  (/ b a))

(builtins)

(let ((financisto (read-canonical "~/common/qs/qs-scratch/financisto-full.csv"))
      (handelsbanken (read-canonical "~/common/qs/qs-scratch/handelsbanken-full.csv")))
  (print "writing financisto-as-csv.csv with headers" (headers financisto))
  (write-csv financisto "/tmp/financisto-as-csv.csv")
  (print "filtering app data")
  (write-csv (filter-sheet financisto "account" "Sterling cash")
             "/tmp/app-sterling.csv")
  (print "writing handelsbanken-as-csv.csv with headers" (headers handelsbanken))
  (write-csv handelsbanken "/tmp/handelsbanken-as-csv.csv")
  (print "converting bank statement from sheet to account")
  (let ((statement-as-account (account "HB current statement" handelsbanken)))
    (print "writing handelsbanken-as-account.csv with" (length (payees statement-as-account)) "payees")
    (write-csv statement-as-account "/tmp/handelsbanken-as-account.csv"))
  (print "converting app data from sheet to account")
  (let ((app-as-account (account "Handelsbanken current account" financisto)))
    (print "writing financisto-as-account.csv with" (length (payees app-as-account)) "payees")
    (write-csv app-as-account "/tmp/financisto-as-account.csv")
    (print "making monthly summary")
    (write-csv (by-month app-as-account) "/tmp/financisto-monthly.csv")
    (print "merging sheet" handelsbanken "into account" app-as-account)
    (let ((added-to-account (add-sheet app-as-account handelsbanken '("regular") "/tmp/trace.csv")))
      (print "added to account" added-to-account)
      (write-csv added-to-account "/tmp/added-to-account.csv"))))
