(+ (* 3 4) 5)

(* (+ 3 4) 5)

(let ((a (+ 3 4))
      (b (* 3 4)))
  (/ b a))

(builtins)

(let ((financisto (read-canonical "~/common/qs/qs-scratch/financisto-full.csv"))
      (handelsbanken (read-canonical "~/common/qs/qs-scratch/handelsbanken-full.csv")))
  (print "writing financisto-as-csv.csv with headers" (headers financisto))
  (write-csv financisto "/tmp/financisto-as-csv.csv")
  (print "writing handelsbanken-as-csv.csv with headers" (headers handelsbanken))
  (write-csv handelsbanken "/tmp/handelsbanken-as-csv.csv")
  (print "converting sheets to accounts")
  (let ((app-as-account (account "Handelsbanken current account" financisto))
        (statement-as-account (account "Handelsbanken current account" handelsbanken)))
    (print "writing financisto-as-account.csv with" (length (payees app-as-account)) "payees")
    (write-csv app-as-account "/tmp/financisto-as-account.csv")
    (print "writing handelsbanken-as-account.csv with" (length (payees statement-as-account)) "payees")
    (write-csv statement-as-account "/tmp/handelsbanken-as-account.csv")
    (print "making monthly summary")
    (let ((app-monthly (by-month app-as-account)))
      (write-csv app-monthly "/tmp/financisto-monthly.csv"))
    (print "merging sheet into account")
    (let ((added-to-account (add-sheet app-as-account handelsbanken)))
      (print added-to-account))))
