#!/bin/bash

STATEMENT=${1-$HOME/Downloads/Transactions.csv}
OUTDIR=merge-results

echo "merging latest (or other specified) statement"

# source setupfintest
source setupfinvars

mkdir -p $OUTDIR
rm -rf $OUTDIR/*

echo done setup

./finlisp.py \
    --no-default-config \
    --output-dir $OUTDIR \
    --config $CONFIGDIR/accounts.yaml \
    --config $CONVDIR/conversions.yaml \
    --bind incoming-statement $STATEMENT \
    merge-latest-statement.lisp
