#!/bin/bash

echo merging latest statement

source setupfintest

echo done setup

./finlisp.py --verbose --no-default-config --config $CONFIGDIR/accounts.yaml --config $CONVDIR/conversions.yaml merge-latest-statement.lisp
