#!/bin/bash

STATEMENT=${1-$HOME/Downloads/Transactions.csv}

echo "merging latest (or other specified) statement"

source setupfintest

echo done setup

./finlisp.py --no-default-config \
             --config $CONFIGDIR/accounts.yaml \
             --config $CONVDIR/conversions.yaml \
             --bind incoming-statement $STATEMENT \
             merge-latest-statement.lisp
