#!/bin/bash

QS=~/open-projects/qs/qs
CONFIGDIR=$OPEN_PROJECTS/qs/conf
CONVDIR=$FINANCES
SCRATCH=~/common/scratch/qs

mkdir -p $SCRATCH

HANDELSBANKENFILE=$FINANCES/handelsbanken/handelsbanken.csv
FINANCISTOFILE=$(ls -t $DROPBOX/Apps/financisto/*.csv | head -1)
COMBINEDFILE=$SCRATCH/combiner-output.csv
TRACKINGFILE=$SCRATCH/tracker-output.csv
FINFILE=$SCRATCH/financisto-tmp.csv

rm -f $COMBINEDFILE $TRACKINGFILE $FINFILE

$QS/prepare_financisto $FINANCISTOFILE $FINFILE

$QS/finconv.py \
    --no-default-config \
    --config $CONFIGDIR/accounts.yaml \
    --config $CONVDIR/conversions.yaml \
    --all-rows \
    --output $COMBINEDFILE \
    --output-format combined \
    $FINFILE \
    $HANDELSBANKENFILE

if [ ! -f $COMBINEDFILE ]
then
    echo Failed to produce combined file
    exit 1
fi

echo -n "Produced combined file "
wc -l $COMBINEDFILE

$QS/fintrack.py \
    --no-default-config \
    --config $CONFIGDIR/accounts.yaml \
    --config $CONVDIR/conversions.yaml \
    --output $TRACKINGFILE \
    --output-format combined \
    $COMBINEDFILE

if [ ! -f $TRACKINGFILE ]
then
    echo Failed to produce tracking file
    exit 1
fi

echo -n "Produced tracking file "
wc -l $TRACKINGFILE
