#!/bin/bash
TARBALL=~/qsfiles.tar
ORIGINALS=~/common/qs-playpen
SCRATCH=~/common/qs-scratch
CONFIGDIR=~/open-projects/qs/conf
CONVDIR=~/common/finances
QS=~/open-projects/qs/qs
if [ ! -f $TARBALL ]
then
    echo making $TARBALL from $ORIGINALS
    tar cf $TARBALL -C $ORIGINALS financisto.csv handelsbanken.csv
fi
mkdir -p $SCRATCH
rm -rf $SCRATCH/*
tar xf $TARBALL -C $SCRATCH
echo Running version from $QS
$QS/finconv.py --no-default-config --config $CONFIGDIR/accounts.yaml --config $CONVDIR/conversions.yaml --output $SCRATCH/converter-output.csv --output-format financisto $SCRATCH/handelsbanken.csv
echo -n produced importer file
wc -c -l $SCRATCH/converter-output.csv
$QS/finconv.py --no-default-config --config $CONFIGDIR/accounts.yaml --config $CONVDIR/conversions.yaml --all-rows --output $SCRATCH/combiner-output.csv --output-format combined $SCRATCH/financisto.csv $SCRATCH/handelsbanken.csv
echo -n produced combined file
wc -c -l $SCRATCH/combiner-output.csv
