#!/bin/bash
TARBALL=~/qsfiles.tar
ORIGINALS=~/common/qs-playpen
SCRATCH=~/common/qs-scratch
CONFIGDIR=~/open-projects/github.com/hillwithsmallfields/qs/conf
CONVDIR=~/common/finances
QS=~/open-projects/github.com/hillwithsmallfields/qs/qs
if [ ! -f $TARBALL ]
then
    echo making $TARBALL from $ORIGINALS
    tar cf $TARBALL -C $ORIGINALS financisto.csv handelsbanken.csv
fi
mkdir -p $SCRATCH
rm -rf $SCRATCH/*
tar xf $TARBALL -C $SCRATCH
IMPORTDATE=$(date --iso-8601)
echo Running version from $QS

./finops.py tests.fins

wc /tmp/account-names /tmp/handelsbanken-app.csv /tmp/handelsbanken-statement.csv /tmp/handelsbanken-daily.csv /tmp/handelsbanken-monthly.csv /tmp/handelsbanken-yearly.csv /tmp/statements-oracle.csv /tmp/app-oracle.csv
