#!/bin/bash
TARBALL=~/qsfiles.tar
ORIGINALS=~/common/qs-playpen
SCRATCH=~/common/qs-scratch
CONFIGDIR=~/open-projects/github.com/hillwithsmallfields/qs/conf
CONVDIR=~/common/finances
QS=~/open-projects/github.com/hillwithsmallfields/qs/qs
if [ ! -f $TARBALL ]
then
    echo making $TARBALL from $ORIGINALS
    tar cf $TARBALL -C $ORIGINALS financisto.csv handelsbanken.csv
fi
mkdir -p $SCRATCH
rm -rf $SCRATCH/*
tar xf $TARBALL -C $SCRATCH
IMPORTDATE=$(date --iso-8601)
echo Running version from $QS

./finops.py --confirm-script tests.fins

wc /tmp/account-names /tmp/handelsbanken-app.csv /tmp/handelsbanken-statement.csv /tmp/handelsbanken-app-daily.csv /tmp/handelsbanken-statement-daily.csv /tmp/handelsbanken-app-monthly.csv /tmp/handelsbanken-statement-monthly.csv /tmp/handelsbanken-app-yearly.csv /tmp/handelsbanken-statement-yearly.csv /tmp/handelsbanken-added-from-statement.csv /tmp/statements-oracle.csv /tmp/app-oracle.csv /tmp/handelsbanken-statement-as-financisto.csv /tmp/handelsbanken-added-from-statement-as-financisto.csv /tmp/handelsbanken-added-from-statement-as-financisto-by-daily-summaries.csv
