#!/bin/bash
TARBALL=~/qsfiles.tar
ORIGINALS=~/common/qs-playpen
SCRATCH=~/common/qs-scratch
CONFIGDIR=~/open-projects/github.com/hillwithsmallfields/qs/conf
CONVDIR=~/common/finances
QS=~/open-projects/github.com/hillwithsmallfields/qs/qs
TESTOUT=./test-results
if [ ! -f $TARBALL ]
then
    echo making $TARBALL from $ORIGINALS
    tar cf $TARBALL -C $ORIGINALS financisto.csv handelsbanken.csv
fi
mkdir -p $SCRATCH
rm -rf $SCRATCH/*
tar xf $TARBALL -C $SCRATCH
IMPORTDATE=$(date --iso-8601)
mkdir -p $TESTOUT
rm -rf $TESTOUT/*
echo Running version from $QS

$QS/csv_sheet.py \
    --no-default-config \
    --config $CONFIGDIR/accounts.yaml \
    --config $CONVDIR/conversions.yaml \
    $SCRATCH/handelsbanken.csv > $TESTOUT/csv_sheet.stdout

$QS/canonical_sheet.py \
    --no-default-config \
    --config $CONFIGDIR/accounts.yaml \
    --config $CONVDIR/conversions.yaml \
    $SCRATCH/handelsbanken.csv \
    $SCRATCH/financisto.csv > $TESTOUT/canonical_sheet.stdout

$QS/tracked_sheet.py \
    --no-default-config \
    --config $CONFIGDIR/accounts.yaml \
    --config $CONVDIR/conversions.yaml \
    $SCRATCH/handelsbanken.csv > $TESTOUT/tracked_sheet.stdout

$QS/account.py \
    --no-default-config \
    --config $CONFIGDIR/accounts.yaml \
    --config $CONVDIR/conversions.yaml \
    $SCRATCH/financisto.csv \
    $SCRATCH/handelsbanken.csv > $TESTOUT/account.stdout

$QS/finconv.py \
    --no-default-config \
    --config $CONFIGDIR/accounts.yaml \
    --config $CONVDIR/conversions.yaml \
    --output $SCRATCH/converter-output.csv \
    --message "Import at $IMPORTDATE" \
    --output-format financisto \
    $SCRATCH/handelsbanken.csv > $TESTOUT/finconv-single.stdout

echo -n produced importer file
wc -c -l $SCRATCH/converter-output.csv

$QS/finconv.py \
    --no-default-config \
    --config $CONFIGDIR/accounts.yaml \
    --config $CONVDIR/conversions.yaml \
    --all-rows \
    --output $SCRATCH/combiner-output.csv \
    --output-format combined \
    --base $SCRATCH/financisto.csv \
    $SCRATCH/handelsbanken.csv > $TESTOUT/finconv-combined.stdout

echo -n produced combined file
wc -c -l $SCRATCH/combiner-output.csv

$QS/fintrack.py \
    --verbose \
    --no-default-config \
    --config $CONFIGDIR/accounts.yaml \
    --config $CONVDIR/conversions.yaml \
    --output $SCRATCH/tracker-output.csv \
    --output-format combined \
    $SCRATCH/combiner-output.csv > $TESTOUT/fintrack.stdout

echo -n produced tracker file
wc -c -l $SCRATCH/tracker-output.csv

$QS/findiscrep.py \
    --no-default-config \
    --config $CONFIGDIR/accounts.yaml \
    --config $CONVDIR/conversions.yaml \
    --verbose \
    --output $SCRATCH/discrepancies.csv \
    $SCRATCH/tracker-output.csv > $TESTOUT/findiscrep.stdout

# $QS/diff_sheet.py \
#     --no-default-config \
#     --config $CONFIGDIR/accounts.yaml \
#     --config $CONVDIR/conversions.yaml \
#     --output $SCRATCH/diffs.csv \
#     $SCRATCH/financisto.csv amount \
#     $SCRATCH/handelsbanken.csv amount   

wc $TESTOUT/*
