#!/bin/bash
TARBALL=~/qsfiles.tar
ORIGINALS=~/common/qs-playpen
SCRATCH=~/common/qs-scratch
CONFIGDIR=~/open-projects/github.com/hillwithsmallfields/qs/conf
CONVDIR=~/common/finances
QS=~/open-projects/github.com/hillwithsmallfields/qs/qs
if [ ! -f $TARBALL ]
then
    echo making $TARBALL from $ORIGINALS
    tar cf $TARBALL -C $ORIGINALS financisto-full.csv handelsbanken-full.csv financisto-1-year.csv handelsbanken-1-year.csv financisto-1-month.csv handelsbanken-1-month.csv
fi
mkdir -p $SCRATCH
rm -rf $SCRATCH/*
tar xf $TARBALL -C $SCRATCH
IMPORTDATE=$(date --iso-8601)
echo Running version from $QS

SELECTIONS=${1-1-month 1-year full}

export SELECTION

for SELECTION in $SELECTIONS
do
    export OUTPUT=/tmp/finout/$SELECTION
    echo Running $SELECTION tests with output to $OUTPUT
    mkdir -p $OUTPUT
    rm -fr $OUTPUT/*
    ./finops.py --confirm-script tests.fins
    
    wc $OUTPUT/initial-account-names $OUTPUT/handelsbanken-app.csv $OUTPUT/handelsbanken-statement.csv $OUTPUT/handelsbanken-app-daily.csv $OUTPUT/handelsbanken-statement-daily.csv $OUTPUT/handelsbanken-app-monthly.csv $OUTPUT/handelsbanken-statement-monthly.csv $OUTPUT/handelsbanken-app-yearly.csv $OUTPUT/handelsbanken-statement-yearly.csv $OUTPUT/handelsbanken-added-from-statement.csv $OUTPUT/statements-oracle.csv $OUTPUT/app-oracle.csv $OUTPUT/handelsbanken-statement-as-financisto.csv $OUTPUT/handelsbanken-added-from-statement-as-financisto.csv $OUTPUT/handelsbanken-added-from-statement-as-financisto-by-daily-summaries.csv $OUTPUT/handelsbanken-regular-added-from-statement-as-financisto.csv $OUTPUT/handelsbanken-regular-added-from-statement-as-financisto-by-daily-summaries.csv $OUTPUT/final-account-names
done
