#!/bin/bash

source setupfinvars

OUTDIR=track-results

STATEMENT=$COMMON/finances/handelsbanken/handelsbanken-full.csv
TRANSACTIONSFILE=${1-$COMMON/finances/finances.csv}

mkdir -p $OUTDIR
rm -rf $OUTDIR/*

./finlisp.py \
    --verbose \
    --no-default-config \
    --output-dir $OUTDIR \
    --config $CONFIGDIR/accounts.yaml \
    --config $CONVDIR/conversions.yaml \
    --bind statement-file $STATEMENT \
    --bind main-file $TRANSACTIONSFILE \
    track-balance.lisp
