#!/bin/bash
export PYTHONPATH=$PYTHONPATH:/$OPEN_PROJECTS/JCGS_py_server/
./storage_client.py --query-key /home/jcgs/open-projects/JCGS_py_server/querykey.pub --reply-key /home/jcgs/open-projects/JCGS_py_server/replykey $*
